export const awards = [
  {
    name: "nZero",
    type: "⤦",
    project: "Identity & Web Design",
    label: "2024",
  },
  {
    name: "Sturdy",
    type: "⤦",
    project: "Web & Design Direction",
    label: "2023",
  },
  {
    name: "Alza",
    type: "⤦",
    project: "Brand Identity",
    label: "2023",
  },
  {
    name: "Equinox",
    type: "⤦",
    project: "Digital Product",
    label: "2021",
  },
  {
    name: "NBC Sports",
    type: "⤦",
    project: "Web Design",
    label: "2022",
  },
  {
    name: "Tovala",
    type: "⤦",
    project: "Web Design",
    label: "2022",
  },
  {
    name: "Arcadia",
    type: "⤦",
    project: "Web Design",
    label: "2023",
  },
  {
    name: "Seriusxm",
    type: "⤦",
    project: "Digital Campaign",
    label: "2023",
  },
  {
    name: "Televisa Univision",
    type: "⤦",
    project: "Web & App",
    label: "2022",
  },
  {
    name: "Las Carpetas",
    type: "⤦",
    project: "Exhibition & Editorial Design",
    label: "2021",
  },
  {
    name: "Amazon AWS",
    type: "⤦",
    project: "Brand Identity & Direction",
    label: "2025",
  },
  {
    name: "Giant",
    type: "⤦",
    project: "Brand Identity & Direction",
    label: "2021",
  },
  {
    name: "Fine Knives",
    type: "⤦",
    project: "Brand Identity & Direction",
    label: "2021",
  },
  {
    name: "KPRS",
    type: "⤦",
    project: "Web Design & Direction",
    label: "2020",
  },
  {
    name: "LunarCrush",
    type: "⤦",
    project: "Web Design & UX",
    label: "2022",
  },
  {
    name: "Proven",
    type: "⤦",
    project: "Brand Identity",
    label: "2021",
  },
  {
    name: "Study Hall",
    type: "⤦",
    project: "Creative & Design Direction",
    label: "2021",
  },
  {
    name: "PLT Golf",
    type: "⤦",
    project: "Brand Identity & Direction",
    label: "2025",
  },
  {
    name: "Renew",
    type: "⤦",
    project: "Brand Identity & Web Design",
    label: "2023",
  },
  {
    name: "Union",
    type: "⤦",
    project: "Product & Motion Design",
    label: "2022",
  },
  {
    name: "Hidrante",
    type: "⤦",
    project: "Brand Identity & Web Design",
    label: "2024",
  },
  {
    name: "The Post",
    type: "⤦",
    project: "Web Design",
    label: "2021",
  },
];
